name: Deploy to VPS

on:
  push:
    branches: [ main ]
  workflow_dispatch:  # Allows manual triggering

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      
      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      
      - name: Build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release
      
      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          known_hosts: unnecessary
          if_key_exists: replace
      
      - name: Deploy to VPS
        run: |
          # Create deployment package
          tar -czf deploy.tar.gz \
            target/release/enlightened-cat \
            templates/ \
            static/ \
            src/
          
          # Copy package to server
          scp -o StrictHostKeyChecking=no deploy.tar.gz ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:~/
          
          # Execute deployment commands
          ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} << 'EOF'
            # Extract files
            mkdir -p ~/deploy-temp
            tar -xzf deploy.tar.gz -C ~/deploy-temp
            
            # Stop service
            sudo systemctl stop enlightened-cat.service
            
            # Copy files to production directory
            sudo cp ~/deploy-temp/target/release/enlightened-cat /var/www/the-enlightened-cat/target/release/
            sudo cp -r ~/deploy-temp/templates/* /var/www/the-enlightened-cat/templates/
            sudo cp -r ~/deploy-temp/static/* /var/www/the-enlightened-cat/static/
            sudo cp -r ~/deploy-temp/src/* /var/www/the-enlightened-cat/src/
            
            # Fix permissions
            sudo chown -R www-data:www-data /var/www/the-enlightened-cat
            
            # Start service
            sudo systemctl start enlightened-cat.service
            
            # Clean up
            rm -rf ~/deploy-temp
            rm deploy.tar.gz
            
            # Check service status
            sudo systemctl status enlightened-cat.service
          EOF
